artifacts:
  text-classification:
    path: model.pkl
    desc: Detect whether the given stackoverflow question should have R language tag
    type: model
    labels:
    - nlp
    - classification
    - stackoverflow
stages:
  train:
    cmd: python src/train.py data/features model.pkl
    deps:
    - data/features
    - src/train.py
    params:
    - train.min_split
    - train.n_est
    - train.seed
    outs:
    - model.pkl
  evaluate:
    cmd: python src/evaluate.py model.pkl data/features
    deps:
    - data/features
    - model.pkl
    - src/evaluate.py
    outs:
    - eval/importance.png
    - eval/live/plots:
        cache: false
    - eval/prc:
        cache: false
    metrics:
    - eval/live/metrics.json:
        cache: false
plots:
- ROC:
    template: simple
    x: fpr
    y:
      eval/live/plots/sklearn/roc/train.json: tpr
      eval/live/plots/sklearn/roc/test.json: tpr
- Confusion-Matrix:
    template: confusion
    x: actual
    y:
      eval/live/plots/sklearn/cm/train.json: predicted
      eval/live/plots/sklearn/cm/test.json: predicted
- Precision-Recall:
    template: simple
    x: recall
    y:
      eval/prc/train.json: precision
      eval/prc/test.json: precision
- eval/importance.png
